### ISSUE TITLE
5e sheet background issues

### ISSUE THREAD

**Issue by Nicholaiii** [shevernitskiy/roll20darkcobalt#1]
Refer to the picture:
![image](https://user-images.githubusercontent.com/7280931/128903497-72c4af49-606e-4c57-874b-306db651f3ff.png)

The number input dials are also an eyesore

**Comment by shevernitskiy** [comment]
![image](https://user-images.githubusercontent.com/28886342/129045782-e4e38955-3c07-47ea-a66c-f1c63f1a1174.png)
hmm... do you use the last version of the style?

**Comment by Nicholaiii** [comment]
I do indeed! Before the last version I fixed these things myself, but I removed it all, updated to new version and the issue was back.

**Comment by shevernitskiy** [comment]
Unfortunattely, I can't fix the problem if I can't see it.
But you can try forked slightly reworked style Turrabo/roll20darkred.
