### ISSUE TITLE
There is an error in the selection of Map in roll20

### ISSUE THREAD

**Issue by RowfayDW** [shevernitskiy/roll20darkcobalt#2]
Well it really is a VTT Enhancement Suite compatibility bug in the map select menu that makes it unusable
![image](https://user-images.githubusercontent.com/94769272/142745810-f6d78f84-c9dc-4cdb-996f-f8d206c56c08.png)
I quite like the general design of the interface in this script but if it does not have compatibility with VTTS (VTT Enhancement Suite) it becomes unusable at least as a master.
So I'd like to send you this compatibility suggestion / bug. and if i could make the script compatible with VTTS

**Comment by shevernitskiy** [comment]
Its impossible. VTT and this style change the same thing. If I switch off styling of page dialog, users without VTT will see ugly original white page dialog. You can try manualy edit style. Just comment Page and Playerzone section in style file, lines 2471 - 2626
